name: drone-race
channels:
  - defaults
  - conda-forge
dependencies:
  - pkg-config
  - python=3.14
  - pip
  - cppzmq
  - zeromq
  - cuda=13.2
  - boost-cpp
  - gxx_linux-64=15
  - gcc_linux-64=15
  - cmake
  - conda-forge::ncurses
  - pip:
    - tqdm
    - numpy
    - matplotlib
    - zmq
